title: Claudia Perez # your name (or website title) here
logo: "/images/c.png?raw=true" # your photo (or logo) here
description: > # your text below (remove <br> elements if you don't need line breaks)
  Data Scientist with +2 years of experience in Machine Learning and +4 years of experience in Algorithms design, Algebra, and Coding. Passionate about learning new technologies having strong autodidact skills with highly hands-on experience and complex problem-solving. A great lover of Mathematics and challenges. Has Ph.D. Degree in Computer Science and Mathematics. 
  <a href="https://www.linkedin.com/in/claudiaperezruisanchez/">View My LinkedIn Profile</a> 
  
